# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: VSTest@2
  inputs:
    testSelector: 'testPlan'
    testPlan: '17743'
    testSuite: |
      {

        "id": 17744,

        "name": "Release-1",

        "plan": {

          "id": "17743",

          "name": "17743"

        },

        "testCaseCount": 1,

        "inheritDefaultConfigurations": false,

        "lastUpdatedDate": "0001-01-01T00:00:00",

        "text": "Release-1"

      }
    testConfiguration: '16'
    searchFolder: '$(System.DefaultWorkingDirectory)'